/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  VIEW_TYPE_MINDMAP: () => VIEW_TYPE_MINDMAP,
  default: () => MindMapBridgePlugin2
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/MindMapFileView.ts
var import_obsidian = require("obsidian");
var MindMapFileView = class extends import_obsidian.FileView {
  constructor(leaf, plugin) {
    super(leaf);
    this.iframeEl = null;
    this.isViewerReady = false;
    this.currentJsonText = null;
    this.debounceTimer = null;
    this.handleWindowMessage = (event) => {
      if (!this.iframeEl || !this.iframeEl.contentWindow)
        return;
      if (!event.data || typeof event.data !== "object") {
        return;
      }
      const trustedOrigin = this.getViewerOrigin();
      const isTrustedOrigin = event.origin === trustedOrigin;
      const isOpaqueNullOrigin = event.origin === "null";
      const isCapacitorLocalOrigin = event.origin.startsWith("capacitor://") || event.origin.startsWith("app://") || event.origin.startsWith("file://") || event.origin.includes("localhost");
      if (!isTrustedOrigin && !isOpaqueNullOrigin && !isCapacitorLocalOrigin) {
        return;
      }
      if (event.source !== this.iframeEl.contentWindow && !(event.source === null && isTrustedOrigin)) {
        return;
      }
      if (event.data.type === "MINDMAP_VIEWER_READY") {
        this.isViewerReady = true;
        if (this.currentJsonText) {
          this.postDataToViewer(this.currentJsonText);
        }
      }
    };
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MINDMAP;
  }
  getDisplayText() {
    return this.file ? this.file.basename : "MindMap Viewer";
  }
  getViewerOrigin() {
    try {
      const url = new URL(this.plugin.settings.viewerUrl);
      return url.origin;
    } catch (e) {
      return "https://mindmap.riyasaksena502.workers.dev";
    }
  }
  async setState(state, result) {
    await super.setState(state, result);
    if (state && typeof state.file === "string" && state.file.length > 0) {
      const abstractFile = this.app.vault.getAbstractFileByPath(state.file);
      if (abstractFile instanceof import_obsidian.TFile) {
        this.file = abstractFile;
        await this.onLoadFile(abstractFile);
      }
    }
  }
  getState() {
    const state = super.getState();
    state.file = this.file ? this.file.path : "";
    return state;
  }
  async onOpen() {
    this.containerEl.empty();
    this.containerEl.addClass("mindmap-bridge-view");
    this.addAction("refresh-cw", "Reload MindMap Viewer", () => this.reloadViewer());
    this.addAction("code", "Open as Text / Raw JSON", () => this.openRawJsonEditor());
    window.addEventListener("message", this.handleWindowMessage);
    this.iframeEl = document.createElement("iframe");
    this.iframeEl.addClass("mindmap-bridge-iframe");
    this.iframeEl.addEventListener("load", () => {
      if (this.currentJsonText && this.isViewerReady) {
        this.postDataToViewer(this.currentJsonText);
      }
    });
    this.iframeEl.src = this.plugin.settings.viewerUrl;
    this.containerEl.appendChild(this.iframeEl);
  }
  async onLoadFile(file) {
    this.file = file;
    try {
      const content = await this.app.vault.read(file);
      this.currentJsonText = content;
      if (this.isViewerReady) {
        this.postDataToViewer(content);
      }
    } catch (err) {
      new import_obsidian.Notice(`Failed to read MindMap file: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
  async onUnloadFile(file) {
    this.currentJsonText = null;
    if (this.debounceTimer) {
      window.clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
    await super.onUnloadFile(file);
  }
  async onClose() {
    window.removeEventListener("message", this.handleWindowMessage);
    this.isViewerReady = false;
    this.currentJsonText = null;
    if (this.debounceTimer) {
      window.clearTimeout(this.debounceTimer);
      this.debounceTimer = null;
    }
    if (this.iframeEl) {
      this.iframeEl.remove();
      this.iframeEl = null;
    }
  }
  handleFileModification(file) {
    if (this.file && file.path === this.file.path) {
      if (this.debounceTimer) {
        window.clearTimeout(this.debounceTimer);
      }
      this.debounceTimer = window.setTimeout(async () => {
        if (this.file && this.file.path === file.path) {
          const content = await this.app.vault.read(this.file);
          this.currentJsonText = content;
          if (this.isViewerReady) {
            this.postDataToViewer(content);
          }
        }
      }, this.plugin.settings.debounceMs);
    }
  }
  postDataToViewer(jsonString) {
    if (this.iframeEl && this.iframeEl.contentWindow) {
      const targetOrigin = this.getViewerOrigin();
      const message = {
        type: "MINDMAP_DATA",
        version: 1,
        payload: jsonString
      };
      try {
        this.iframeEl.contentWindow.postMessage(message, targetOrigin);
      } catch (e) {
      }
    }
  }
  reloadViewer() {
    this.isViewerReady = false;
    if (this.iframeEl) {
      this.iframeEl.src = this.plugin.settings.viewerUrl;
    }
  }
  async openRawJsonEditor() {
    if (!this.file)
      return;
    await this.plugin.openFileAsRawJson(this.file, this.leaf);
  }
};

// src/Settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  viewerUrl: "https://mindmap.riyasaksena502.workers.dev",
  autoRefreshOnSave: true,
  debounceMs: 300
};
var MindMapBridgeSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "MindMap Bridge Settings" });
    new import_obsidian2.Setting(containerEl).setName("Viewer URL").setDesc("Cloudflare-hosted Mind Map Viewer endpoint").addText(
      (text) => text.setPlaceholder("https://mindmap.riyasaksena502.workers.dev").setValue(this.plugin.settings.viewerUrl).onChange(async (value) => {
        this.plugin.settings.viewerUrl = value.trim() || DEFAULT_SETTINGS.viewerUrl;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Auto-refresh on save").setDesc("Automatically update the Mind Map view when the local JSON file is saved").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRefreshOnSave).onChange(async (value) => {
        this.plugin.settings.autoRefreshOnSave = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Debounce buffer (ms)").setDesc("Delay in milliseconds before sending updated JSON to viewer on file edit").addSlider(
      (slider) => slider.setLimits(100, 1e3, 50).setValue(this.plugin.settings.debounceMs).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.debounceMs = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var VIEW_TYPE_MINDMAP = "mindmap-json-view";
var MindMapBridgePlugin2 = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_MINDMAP,
      (leaf) => new MindMapFileView(leaf, this)
    );
    this.registerExtensions(["mindmap.json"], VIEW_TYPE_MINDMAP);
    this.addSettingTab(new MindMapBridgeSettingTab(this.app, this));
    this.registerEvent(
      this.app.vault.on("modify", (file) => {
        if (this.settings.autoRefreshOnSave && file instanceof import_obsidian3.TFile) {
          this.app.workspace.iterateAllLeaves((leaf) => {
            if (leaf.view instanceof MindMapFileView) {
              leaf.view.handleFileModification(file);
            }
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-open", (file) => {
        var _a;
        if (file && this.isMindMapFile(file)) {
          const existingMindMapLeaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_MINDMAP).find(
            (l) => {
              var _a2;
              return l.view instanceof MindMapFileView && ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
            }
          );
          if (existingMindMapLeaf) {
            this.app.workspace.revealLeaf(existingMindMapLeaf);
            return;
          }
          const activeFileView = this.app.workspace.getActiveViewOfType(import_obsidian3.FileView);
          const targetLeaf = activeFileView && ((_a = activeFileView.file) == null ? void 0 : _a.path) === file.path ? activeFileView.leaf : this.getLeafForFile(file);
          if (targetLeaf && targetLeaf.view.getViewType() !== VIEW_TYPE_MINDMAP) {
            this.openFileInMindMapViewer(file, targetLeaf);
          }
        }
      })
    );
    this.app.workspace.onLayoutReady(() => {
      this.scanAndConvertMindMapLeaves();
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (file instanceof import_obsidian3.TFile) {
          if (this.isMindMapFile(file) || this.isJsonFile(file)) {
            menu.addItem((item) => {
              item.setTitle("Open as Mind Map").setIcon("network").onClick(() => this.openFileInMindMapViewer(file));
            });
          }
          if (this.isMindMapFile(file)) {
            menu.addItem((item) => {
              item.setTitle("Open as Text / Raw JSON").setIcon("code").onClick(() => this.openFileAsRawJson(file));
            });
          }
        } else if (file instanceof import_obsidian3.TFolder) {
          menu.addItem((item) => {
            item.setTitle("New MindMap JSON File").setIcon("file-plus").onClick(() => this.createNewMindMapFile(file.path));
          });
        }
      })
    );
    this.addCommand({
      id: "open-active-file-as-mindmap",
      name: "Open active file as Mind Map",
      callback: () => {
        this.debugWorkspaceState();
        const targetFile = this.getActiveJsonFile();
        if (targetFile) {
          this.openFileInMindMapViewer(targetFile);
        } else {
          new import_obsidian3.Notice("No active JSON or MindMap file found. Please select or open a file first.");
        }
      }
    });
    this.addCommand({
      id: "refresh-current-mindmap",
      name: "Refresh current Mind Map",
      checkCallback: (checking) => {
        const activeLeaf = this.app.workspace.getActiveViewOfType(MindMapFileView);
        if (activeLeaf) {
          if (!checking) {
            activeLeaf.reloadViewer();
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "create-new-mindmap-file",
      name: "Create new MindMap JSON file",
      callback: () => this.createNewMindMapFile()
    });
    this.addRibbonIcon("network", "Open MindMap Viewer", () => {
      this.debugWorkspaceState();
      const activeFile = this.getActiveJsonFile();
      if (activeFile) {
        this.openFileInMindMapViewer(activeFile);
      } else {
        new import_obsidian3.Notice("No active JSON or MindMap file found. Please select or open a file first.");
      }
    });
  }
  async onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_MINDMAP);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  isMindMapFile(file) {
    if (!file)
      return false;
    return file.name.toLowerCase().endsWith(".mindmap.json");
  }
  isJsonFile(file) {
    if (!file)
      return false;
    return file.extension.toLowerCase() === "json";
  }
  debugWorkspaceState() {
    var _a, _b, _c;
    const workspace = this.app.workspace;
    const activeView = workspace.getActiveViewOfType(import_obsidian3.FileView);
    console.log("=== DIAGNOSTICS: Workspace State ===");
    console.log("1. workspace.getActiveFile():", (_a = workspace.getActiveFile()) == null ? void 0 : _a.path);
    console.log("2. workspace.getActiveViewOfType(FileView)?.file:", (_b = activeView == null ? void 0 : activeView.file) == null ? void 0 : _b.path);
    const mostRecentLeafFile = ((_c = workspace.getMostRecentLeaf()) == null ? void 0 : _c.view) && "file" in workspace.getMostRecentLeaf().view ? workspace.getMostRecentLeaf().view.file : void 0;
    console.log("3. workspace.getMostRecentLeaf()?.view?.file:", mostRecentLeafFile instanceof import_obsidian3.TFile ? mostRecentLeafFile.path : mostRecentLeafFile);
    const activeFile = this.getCurrentVaultFile();
    console.log("4. Resolved active file:", activeFile ? {
      name: activeFile.name,
      path: activeFile.path,
      extension: activeFile.extension
    } : null);
    workspace.iterateAllLeaves((leaf) => {
      const leafFile = "file" in leaf.view ? leaf.view.file : null;
      console.log(`Leaf: viewType=${leaf.view.getViewType()}, file=${leafFile == null ? void 0 : leafFile.path}, name=${leafFile == null ? void 0 : leafFile.name}`);
    });
    console.log("=== END DIAGNOSTICS ===");
  }
  getCurrentVaultFile() {
    const workspace = this.app.workspace;
    const activeFileView = workspace.getActiveViewOfType(import_obsidian3.FileView);
    if (activeFileView && activeFileView.file instanceof import_obsidian3.TFile) {
      return activeFileView.file;
    }
    const activeFile = workspace.getActiveFile();
    if (activeFile instanceof import_obsidian3.TFile) {
      return activeFile;
    }
    const mostRecentLeaf = workspace.getMostRecentLeaf();
    if (mostRecentLeaf && mostRecentLeaf.view && "file" in mostRecentLeaf.view) {
      const file = mostRecentLeaf.view.file;
      if (file instanceof import_obsidian3.TFile) {
        return file;
      }
    }
    return null;
  }
  getActiveJsonFile() {
    const file = this.getCurrentVaultFile();
    if (file && (this.isMindMapFile(file) || this.isJsonFile(file))) {
      return file;
    }
    return null;
  }
  getLeafForFile(file) {
    let foundLeaf = null;
    this.app.workspace.iterateAllLeaves((leaf) => {
      var _a;
      if (leaf.view instanceof import_obsidian3.FileView && ((_a = leaf.view.file) == null ? void 0 : _a.path) === file.path) {
        foundLeaf = leaf;
      }
    });
    return foundLeaf || this.app.workspace.getMostRecentLeaf();
  }
  scanAndConvertMindMapLeaves() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian3.FileView && leaf.view.file && this.isMindMapFile(leaf.view.file)) {
        if (leaf.view.getViewType() !== VIEW_TYPE_MINDMAP) {
          this.openFileInMindMapViewer(leaf.view.file, leaf);
        }
      }
    });
  }
  async openFileInMindMapViewer(file, targetLeaf) {
    var _a;
    let leaf = targetLeaf;
    if (!leaf) {
      leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_MINDMAP).find(
        (l) => {
          var _a2;
          return l.view instanceof MindMapFileView && ((_a2 = l.view.file) == null ? void 0 : _a2.path) === file.path;
        }
      ) || null;
    }
    if (!leaf) {
      const activeFileView = this.app.workspace.getActiveViewOfType(import_obsidian3.FileView);
      if (activeFileView && ((_a = activeFileView.file) == null ? void 0 : _a.path) === file.path) {
        leaf = activeFileView.leaf;
      } else {
        leaf = this.app.workspace.getLeaf(false);
      }
    }
    await leaf.setViewState({
      type: VIEW_TYPE_MINDMAP,
      state: { file: file.path },
      active: true
    });
    this.app.workspace.revealLeaf(leaf);
  }
  async openFileAsRawJson(file, targetLeaf) {
    const leaf = targetLeaf || this.app.workspace.getLeaf(false);
    await leaf.openFile(file, { active: true });
  }
  async createNewMindMapFile(parentFolderPath) {
    var _a;
    const fileName = `mindmap-${Date.now()}.mindmap.json`;
    const initialContent = JSON.stringify(
      {
        id: "new-mindmap",
        title: "New Mind Map",
        subject: "General",
        language: "en",
        root: {
          id: "root",
          label: "New Mind Map",
          children: []
        }
      },
      null,
      2
    );
    let targetPath;
    if (parentFolderPath) {
      targetPath = (0, import_obsidian3.normalizePath)(`${parentFolderPath}/${fileName}`);
    } else {
      const activeFile = this.getActiveJsonFile();
      const parentFolder = this.app.fileManager.getNewFileParent((_a = activeFile == null ? void 0 : activeFile.path) != null ? _a : "");
      targetPath = (0, import_obsidian3.normalizePath)(`${parentFolder.path}/${fileName}`);
    }
    try {
      const createdFile = await this.app.vault.create(targetPath, initialContent);
      await this.openFileInMindMapViewer(createdFile);
      new import_obsidian3.Notice(`Created ${createdFile.name}`);
    } catch (err) {
      new import_obsidian3.Notice(`Error creating file: ${err instanceof Error ? err.message : String(err)}`);
    }
  }
};
